#!/usr/bin/env bash
# Display "To infinity & beyond" indefinitely with sleep 2 between iteratio
# Displays "I am invincible!!!" in between each iteration.

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible!!!"' SIGTERM 
done
